### PR TITLE
German Translation Update

### PR DESCRIPTION
**Pull request by SoongNoonien**
The German translation was very incomplete so I decided to update it. While doing it I found one line in `GMDatabaseSource.cpp` which wasn't translatable yet. I also found two dubious translation strings which weren't that easy to fix. 

The first one is in line 78 of the original `gogglesmm.pot`. In some files the string 'No' stands for 'Track number' and in the rest of the files for 'No' in terms of 'No, I don't want it'. In English both strings are 'No' but in German it would be something like 'Nr.' and 'Nein'. Because German isn't the only language where these to meanings have to be distinguished, I'd consider this an issue.

The second one is in line 380. In one file 'Tag' means actually 'Tag' and in rest of the files it rather seems to mean 'Genre' but I'am not sure how it is intended.

My suggestion for a distinction would be:
```
src/GMFilterSource.cpp:197 src/GMPlayListSource.cpp:387
'No' in terms of 'No, I don't want it'

src/GMDatabaseSource.cpp:226 src/GMPlayQueue.cpp:67 src/GMStreamSource.cpp:58
'No' in terms of 'Track number'

src/GMFilterEditor.cpp:47 src/GMStreamSource.cpp:156 src/GMTrackView.cpp:264
rather 'Genre'

src/GMImportDialog.cpp:498
'Tag'
```

So what do you mean?

### CODE REVIEW

**Comment by gogglesguy** [comment]
Thanks for the update. I'll have to take a look at some of the translation issues. I'm sure there's a generic solution available.

**Comment by gogglesguy** [comment]
@SoongNoonien sorry it took a while. 

The track number vs nein was easily resolved as the "nein" was missing an mnemonic underline so "No" becomes "&No". 

Regarding Genre vs Tag. The one in ImportDialog does refer to a File Tag (id3v2, id3v1 etc), but the other ones refer to generic tags or labels, which may include "genre". I used to use "Genre" here, but I felt that was too restricted as you may still want to label your music to something that isn't strictly a genre. So I changed the naming to the generic tag instead. I don't know how this would affect your translation?

**Comment by SoongNoonien** [comment]
I'm very sorry but I don't use gogglesmm anymore.

> I don't know how this would affect your translation?

I think it should be fine.

**Comment by gogglesguy** [comment]
> I'm very sorry but I don't use gogglesmm anymore.
> 
> > I don't know how this would affect your translation?
> 
> I think it should be fine.

Thanks!

**Pull request merged**
